### ISSUE TITLE
`this` parses as an identifier

### ISSUE THREAD

**Issue by robrix** [maxbrunsfeld/tree-sitter-javascript#2]
I feel like it should probably be categorized in its own right. At the very least this would allow it to be syntax highlighted differently.

**Comment by maxbrunsfeld** [comment]
> it should probably be categorized in its own right

Yeah, that's probably true. Maybe `arguments` too. It could be its own type of expression. Do you feel like adding that?

**Comment by robrix** [comment]
I’d be happy to give it a shot :+1:
